### PR TITLE
Add Comment and CommentVote Models

### PR DESCRIPTION
**Pull request by MojixCoder**
Comment Model supports leaving comments for whether Answer or Question.

### CODE REVIEW

**Comment by MojixCoder** [comment]
more info about (GenericRelations)[https://docs.djangoproject.com/en/1.8/ref/contrib/contenttypes/#generic-relations]

**Comment by mshirdel** [comment]
No need to change any setting for this issue. Please use development.py for settings in your local environment. For more information see README file.
I assign you to this feature in project to-dos if you can complete this by adding views and template (If you like)

**Comment by MojixCoder** [comment]
> No need to change any setting for this issue. Please use development.py for settings in your local environment. For more information see README file.
> I assign you to this feature in project to-dos if you can complete this by adding views and template (If you like)

**Comment by MojixCoder** [comment]
I'm not a front-end developer but i can add views, Thanks.

**Comment by mshirdel** [comment]
No problem. Thanks.

**Comment by MojixCoder** [comment]
am I allowed to use `rest_framework` for leaving comments?

**Comment by mshirdel** [comment]
We don't user DRF.

**Pull request closed without merging**
